FROM nginx:alpine

COPY workflows-inference /usr/share/nginx/html/workflows-inference
COPY workflows-write-rawxml /usr/share/nginx/html/workflows-write-rawxml
COPY workflows-evaluation /usr/share/nginx/html/workflows-evaluation