FROM nginx:alpine
COPY write-rawxml-index.html /usr/share/nginx/html/index.html
COPY style.css         /usr/share/nginx/html/style.css
COPY favicon.ico       /usr/share/nginx/html/favicon.ico
COPY TheFlow_white.png /usr/share/nginx/html/TheFlow_white.png
